config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :offers do 
    get "/bookings", to: "bookings#index"
  end
  resources :bookings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/dashboard", to: "pages#dashboard", :as => :user_root
  get "/profile", to: "pages#profile"
  get "/ride_history", to: "pages#ride_history"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer
  has_many :evaluations
  validates :departing_from, :going_to, presence: true
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :booking
end

app/models/offer.rb
class Offer < ApplicationRecord
    belongs_to :user
    validates :price_per_km, :available_seats, :car_model, :car_photo, presence: true
    has_one_attached :car_photo
    has_many :bookings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :offers, dependent: :destroy
  has_many :bookings, :through => :offers
  has_one_attached :avatar
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  include Pundit
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :postal_code, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :postal_code, :avatar])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    
  def index
    @bookings = Booking.all
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @booking = Booking.new
    @offers = Offer.all
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    authorize @booking
    if @booking.save!
      redirect_to booking_path(@booking)
    else
      @booking = Booking.new(booking_params)
      render :new
    end  
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
    render :new
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to bookings_path
  end

  private
  def booking_params
    params.require(:booking).permit(:departing_from, :going_to, :estimated_pickup_time, :date, :pick_up_time, :status, :offer_id)
  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  def index
    @offers = Offer.all
    @offers = policy_scope(Offer).order(created_at: :desc)
  end

  def show
    @offer = Offer.find(params[:id])
    authorize @offer
  end

  def new
    @offer = Offer.new
    authorize @offer
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    authorize @offer
    if @offer.save!
      redirect_to offer_path(@offer)
    else
      @offer = Offer.new(offer_params)
      render :new
    end  
  end

  def edit
    @offer = Offer.find(params[:id])
    authorize @offer
    render :new
  end

  def update
    @offer = Offer.find(params[:id])
    authorize @offer
    @offer.update(offer_params)
    redirect_to offer_path(@offer)
  end

  def destroy
    @offer = Offer.find(params[:id])
    authorize @offer
    @offer.destroy
    redirect_to offers_path
  end

  private
  def offer_params
    params.require(:offer).permit(:car_model, :car_photo, :price_per_km, :available_seats)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
  end

  def profile
  end

  def ride_history
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="flex-grow-1">
<h1 class="text-center mt-5">Bookings</h1>
<ul class="drivers-list mt-4">

<% @bookings.each do |booking| %>
<li class="drivers-list-item ">
<div class="card-car">
  <%= cl_image_tag booking.offer.car_photo.key %>
  <div class="card-car-infos">
    <div>
      <h2><%= booking.offer.car_model %></h2>
      <p>Driven by: <%= booking.offer.user.full_name %></p>
    </div>
    <h2 class="card-car-pricing"><%= booking.offer.price_per_km.floor %> USD</h2>
    <%= cl_image_tag booking.offer.user.avatar.key, class: "card-car-user avatar-bordered" %>
  </div>

  <% if policy(booking).edit? %>
  <%= link_to 'Edit', edit_booking_path(booking), class: "d-flex justify-content-center" %>
  <% end %>

</div>
</li>
<% end %>
</ul>
</div>

app/views/bookings/new.html.erb
<div class="flex-grow-1">
<h1 class="text-center mt-5">Book a ride</h1>
<%= simple_form_for @booking do |b| %>
<div class="form-inputs container bg-light bg-gradient justify-content-center mt-5">
  <%= b.input :departing_from, label: "From :", label_html: { class: 'my_class' } %>
  <%= b.input :going_to, label: "To :", label_html: { class: 'my_class' } %>
  <%= b.association :offer, collection: Offer.all.map {|o| [o.car_model, o.id]}, label: "Choose your ride", label_html: { class: 'my_class' } %>
</div>
<div class="d-flex flex-column align-items-center">
  <div class="form-actions">
    <%= b.button :submit, "Request a ride", class: "btn btn-lg btn-dark my-2" %>
  </div>
<% end %>
</div>

app/views/bookings/show.html.erb
<div class="card-car  mx-5 mt-5 w-50 h-50">
  <%= cl_image_tag @booking.offer.car_photo.key %>
  <div class="card-car-infos">
    <div>
      <h2><%= @booking.offer.car_model %></h2>
      <p>Driven by: <%= @booking.offer.user.full_name %></p>
      <p>Destination: <%= @booking.going_to %></p>
    </div>
    <h2 class="card-car-pricing"><%= @booking.offer.price_per_km.floor %> USD</h2>
    <%= cl_image_tag @booking.offer.user.avatar.key, class: "card-car-user avatar-bordered" %>
  </div>
  <div class="d-flex justify-content-between">
    <% if policy(@booking).edit? %>
        <%= link_to 'Edit', edit_booking_path(@booking) %>
    <% end %>
    <%= link_to "Return to Driver's list", bookings_path(@bookings) %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ubercopycat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
  <div class="d-flex flex-column min-vh-100 vh-100">
    <!-- app/views/layouts/application.html.erb -->
      <% if current_user.present? %>
      <div class="d-inline-flex min-vh-100 vh-100">
        <%= render :partial => "shared/sidebars" %>
        <%= yield %>
      </div>
      <% else %>
        <%= render 'shared/navbar' %>
            <%= yield %>
        <%= render 'shared/footer' %>
      <% end %>
    <!-- app/views/layouts/application.html.erb -->
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/offers/index.html.erb
<div class="flex-grow-1">
<h1 class="text-center mt-5">Our drivers</h1>
<ul class="drivers-list mt-4">

<% @offers.each do |offer| %>
<li class="drivers-list-item ">
<div class="card-car">
  <%= cl_image_tag offer.car_photo.key %>
  <div class="card-car-infos">
    <div>
      <h2><%= offer.car_model %></h2>
      <p>Driven by: <%= offer.user.full_name %></p>
    </div>
    <h2 class="card-car-pricing"><%= offer.price_per_km.floor %> USD</h2>
    <%= cl_image_tag offer.user.avatar.key, class: "card-car-user avatar-bordered" %>
  </div>

  <% if policy(offer).edit? %>
  <%= link_to 'Edit', edit_offer_path(offer), class: "d-flex justify-content-center" %>
  <% end %>

</div>
</li>
<% end %>
</ul>
</div>

app/views/offers/new.html.erb
<div class="flex-grow-1">
<h1 class="text-center mt-5">Register a new car</h1>
<%= simple_form_for @offer do |o| %>
<div class="form-inputs container bg-light bg-gradient justify-content-center mt-5">
  <%= o.input :car_model, label: "Enter your car model:", label_html: { class: 'my_class' } %>
  <%= o.input :price_per_km, label: "Price per Kilometer:", label_html: { class: 'my_class' } %>
  <%= o.input :available_seats, label: "Number of available seats:", label_html: { class: 'my_class' } %>
  <%= o.input :car_photo, as: :file, input_html: { data: { direct_upload_url: '/rails/active_storage/direct_uploads' } } %>
</div>
<div class="d-flex flex-column align-items-center">
  <div class="form-actions">
    <%= o.button :submit, class: "btn btn-lg btn-dark my-2" %>
  </div>
<% end %>
</div>

app/views/offers/show.html.erb
<div class="card-car">
  <%= cl_image_tag @offer.car_photo.key %>
  <div class="card-car-infos">
    <div>
      <h2><%= @offer.car_model %></h2>
      <p>Driven by: <%= @offer.user.full_name %></p>
    </div>
    <h2 class="card-car-pricing"><%= @offer.price_per_km.floor %> USD</h2>
    <%= cl_image_tag @offer.user.avatar.key, class: "card-car-user avatar-bordered" %>
  </div>
  <div class="d-flex justify-content-between">
    <% if policy(@offer).edit? %>
        <%= link_to 'Edit', edit_offer_path(@offer) %>
    <% end %>
    <%= link_to "Return to Driver's list", offers_path(@offers) %>
    </div>
</div>

app/views/pages/home.html.erb
<div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" id="carousel-1">
      <h1 class="display-4">Find a ride today!</h1>
      <hr class="my-3">
      <p class="lead">Focused on safety, wherever you go</p>
      <hr class="my-1">
      <p>Register to enjoy a dependable and readily available transportation service.</p>
      <hr class="my-2">
      <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-dark btn-lg sign-up-button" %>
    </div>
    <div class="carousel-item" id="carousel-2">
      <h1 class="display-4">Find a ride today!</h1>
      <hr class="my-3">
      <p class="lead">Focused on safety, wherever you go</p>
      <hr class="my-1">
      <p>Register to enjoy a dependable and readily available transportation service.</p>
      <hr class="my-2">
      <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-dark btn-lg sign-up-button" %>
    </div>
    <div class="carousel-item" id="carousel-3">
      <h1 class="display-4">Find a ride today!</h1>
      <hr class="my-3">
      <p class="lead">Focused on safety, wherever you go</p>
      <hr class="my-1">
      <p>Register to enjoy a dependable and readily available transportation service.</p>
      <hr class="my-2">
      <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-dark btn-lg sign-up-button" %>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden"></span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden"></span>
  </button>
</div>

app/views/pages/profile.html.erb
<div class="flex-grow-1 ml-5 mt-4 mr-4">
<h1 class="text-center mt-2">Profile</h1>
<div class="d-inline-flex justify-content-around">
  <%= image_tag current_user.avatar, style: "width: 250px; height: 220px", class: "flex-fill" %>
  <div class="d-flex flex-column ml-2 flex-fill">
    <h4>Full name :</h4>
    <p><%= current_user.full_name %></p>
    <h4>Email :</h4>
    <p><%= current_user.email %></p>
    <h4>Postal code :</h4>
    <p><%= current_user.postal_code %></p>
  </div>
</div>
<div class = "mt-5">
  <h4>My cars :</h4>
  <div class = "d-flex mt-4">
    <% current_user.offers.each do |o| %>
      <div class="d-flex flex-column ml-2 flex-fill ">
        <p style="text-align:center"><%= o.car_model %></p>
        <%= image_tag o.car_photo, style: "width: 100%; height: 180px; object-fit: cover;" %>
        <%= link_to 'Edit', edit_offer_path(o), class: "d-flex justify-content-center" %>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/pages/ride_history.html.erb
    <% current_user.bookings.each do |b| %>
      <div class="d-flex flex-column ml-2 flex-fill ">
        <p style="text-align:center"><%= b.departing_from %></p>
        <p style="text-align:center"><%= b.going_to %></p>
        <p style="text-align:center"><%= b.status %></p>
      </div>
    <% end %>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    <i class="fa fa-copyright" aria-hidden="true"></i> copyright ubercopycat
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-image: linear-gradient(to left, #000000 , #2d3436);">
  <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", "/dashboard", class: "dropdown-item" %>
              <%= link_to "Driver mode", "#", class: "dropdown-item" %>
              <%= link_to "Search for a ride", "#", class: "dropdown-item" %>
              <%= link_to "Add a new car", "/offers/new", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

          <li class="nav-item">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Drivers", "/offers", class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link glow-on-hover d-flex justify-content-center align-items-center" %>
          </li>
          <li class="nav-item"><%= link_to "Home", "/", class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>

    <%= link_to "/", class: "navbar-brand" do %>
      <%= cl_image_tag("ne32nquvvsdtafuomhfa.jpg", width: 600, height: 200, crop: :fit) %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>

app/views/shared/_sidebars.html.erb
<div class="d-flex flex-column vh-100 flex-shrink-0 p-3 text-white" style="width: 250px; background-image: linear-gradient(to left, #000000 , #2d3436);"> 
    <a href="/dashboard" class="d-flex align-items-center justify-content-center mb-2 mb-md-0 me-md-auto text-white text-decoration-none"> 
        <span>Welcome</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li> <%= link_to "Dashboard", "/dashboard", class: "dropdown-item active text-white sidebar-link" %> </li>
        <li> <%= link_to "Add a new car", "/offers/new", class: "dropdown-item text-white sidebar-link" %> </li>
        <li> <%= link_to "Drivers", "/offers", class: "dropdown-item text-white sidebar-link" %> </li>
        <li> <%= link_to "Book a ride", "/bookings/new", class: "dropdown-item text-white sidebar-link" %> </li>  
        <li> <%= link_to "Ride History", "/ride_history/", class: "dropdown-item text-white sidebar-link" %> </li>  
        <li> <%= link_to "Bookings", "/bookings", class: "dropdown-item text-white sidebar-link" %> </li> 
    </ul>
    <hr>
    <div class="dropdown d-flex align-items-center"> <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false"> <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %> <strong class="pl-2"> <%= current_user.full_name %></strong> </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li> <%= link_to "Profile", "/profile", class: "dropdown-item" %> </li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
        </ul>
         <div class="online-badge ml-2"></div> 
    </div>
</div>